### ISSUE TITLE
Leather Armour

### ISSUE THREAD

**Issue by SpecialN** [aarontwf/BattleNight-Core#105]
Is there a way to add colours to armour. If so, how?

**Comment by aarontwf** [comment]
Yes it is possible with v1.8.0.  If you still have a the default classes have a look at the Medic class.  Under <code>classes.Medic.armour.helmet</code> in Classes.yml there is a leather helmet with a pink colour.  The colour is under the <code>colour</code> tag in RGB format.  For any armour you want coloured add this tag with the colour you want it to be.

Hope this helped, if your still a bit stuck just ask and I can post an example.

**Comment by SpecialN** [comment]
What are the values of the colours? Like which number represents which colour?
Thanks for the speedy reply

**Comment by aarontwf** [comment]
Okay so here 177 is red, 93 is green and 155 is blue.  The format is <code>R, G, B</code>

``` yaml
classes:
    Medic:
        armour:
            helmet:
                type: leather_helmet
                enchantments: 0~2
                colour: 177, 93, 155
```

I'm not sure if your familiar with RGB but for example a solid blue helmet would look like so:

``` yaml
classes:
    Medic:
        armour:
            helmet:
                type: leather_helmet
                enchantments: 0~2
                colour: 0, 0, 225
```

You can use a tool like this http://www.colorpicker.com/ to pick a colour then just copy the R, G and B values in.
