### ISSUE TITLE
some of my things wont work for my new class

### ISSUE THREAD

**Issue by kanti123** [aarontwf/BattleNight-Core#36]
The title tells it , here is the yml in pastebin http://pastebin.com/xHCSNpnD

**Comment by aarontwf** [comment]
Your classes.yml looks fine to me.  Could you give me more details on what doesn't work?

**Comment by kanti123** [comment]
ok so when I choose my class "God" that I made,it has errors on my server log,the thing is I dont get armour, or potians but bottle O'enchanting
http://pastebin.com/GM11a6L8 this is the link of my log, read from the bottem untill player command kanti123 /i ironblock 1

**Comment by aarontwf** [comment]
The error say item 373:16428 does not exist which is correct.  Use [my potion list](http://bit.ly/potionlist) to find the correct ID and Data Value.

**Comment by kanti123** [comment]
no the last item on your page is 373:16428, and armour, i'will see if I take out it will it work

**Comment by aarontwf** [comment]
Try getting rid of all the x<some number> on all potions.

**Comment by kanti123** [comment]
how about armour ( oh and i'l see if that works) is there a limit to what you can have?

**Comment by aarontwf** [comment]
It worked fine for me after a few small changes:

![Custom Class](https://dl.dropbox.com/u/39528590/Plugins/BattleNight/Images/Issues/36-1.png)

Here's the classes.yml:

``` yaml
# BattleNight Version: 1.1.3
# Classes Configuration File
#
# Add Classes as you wish but do not use spaces in names.
# Items are i:dxa, i=Item d=data a=Ammount.  Data and ammount are optional
# Each class must have at least 2 items, use the dummyitem if you only want 1
# The DummyItem can also be used as a spacer (examples bellow)
# Remember, potions can not be stacked

DummyItem: 6

Classes:
    Pyro:
        Armor: 298,299,300,301
        Items: 259,46x2,6,6,6,6,6,6,373:8195
    Tank:
        Armor: 310,311,312,313
        Items: 272,6
    Swordsman:
        Armor: 306,307,308,309
        Items: 276,6,6,6,6,6,6,6,373:8233
    Archer:
        Armor: 302,303,304,305
        Items: 261,262x64,262x64
    Medic:
        Armor: 298,303,304,305
        Items: 283,6,322x4,6,373:16389,373:16389,373:16385
    Magician:
        Armor: 6,6
        Items: 268,6,373:8258,6,6,373:16388,373:16392,373:16394,373:16396
    God:   
        Armor: 310,311,312,313
        Items: 276x1,261x1,262x64,384x64,116x1,47x64,373:16428,373:16458,373:16489,373:16421,373:16482,373:16489
```
