### ISSUE TITLE
Battlenight Kits Bug

### ISSUE THREAD

**Issue by XxCoolGamesxX** [aarontwf/BattleNight-Core#52]
Hello.   

We have a community that loves your Battlenight plugin but there is a glitch in it at this moment.  We have set kits for pvp but others for the Battlenight plugin.  People are abusing the kits by joining BN - picking a kit, logging out and then when logging back in, doing /mv spawn (which brings them back to the PVP spawn world).  It gives them the kits from BN which we don't want happening but we can't find out how to fix it as it's a bug in your plugin we believe.  

Thanks

**Comment by aarontwf** [comment]
Make sure the command blocker is on in config.yml:

``` yaml
Commands:
    Block: true
    Whitelist: 
        - list
        - me
        - toggledownfall
        - stop
        - reload
```
