### ISSUE TITLE
bn join not working

### ISSUE THREAD

**Issue by ghost** [aarontwf/BattleNight-Core#66]
i have a installation and every command works apart from one of the most crucial:
BN JOIN

Client:an internal server error occured when performing this command
server:14:09:25 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'bn' in plugin BattleNight v1.2.7
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:915)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:828)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:810)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:561)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at me.limebyte.battlenight.core.BattleNight.preparePlayer(BattleNight.java:1079)
    at me.limebyte.battlenight.core.Battle.addPlayer(Battle.java:22)
    at me.limebyte.battlenight.core.BattleNight.onCommand(BattleNight.java:450)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

**Comment by ghost** [comment]
Re-installed
Now I can't pick class

**Comment by aarontwf** [comment]
How are you picking classes?

**Comment by ghost** [comment]
By punching them
anyway it works now but when i try to add classes 'Ninja' and 'samurai'
and bn reload it says reload failed
p.s.when are leaderboards on signs like ma coming?

**Comment by aarontwf** [comment]
What BattleNight version are you using and can I see your classes.yml file?

**Comment by ghost** [comment]
BattleNight version: 1.2.1

classes.yml:

```
# BattleNight Version: 1.2.1
# Classes Configuration File
#
# Add Classes as you wish but do not use spaces in names.
# Items are i:dxa, i=Item d=data a=Ammount.  Data and ammount are optional
# Each class must have at least 2 items, use the dummyitem if you only want 1
# The DummyItem can also be used as a spacer (examples bellow)
# Remember, potions can not be stacked
# I have made a searchable Potion ID list available at http://bit.ly/potionlist

DummyItem: 6

Classes:
    Pyro:
        Armor: 298,299,300,301
        Items: 259,46x2,6,6,6,6,6,6,373:8195
    Tank:
        Armor: 310,311,312,313
        Items: 272,6
    Swordsman:
        Armor: 306,307,308,309
        Items: 276,6,6,6,6,6,6,6,373:8233
    Archer:
        Armor: 302,303,304,305
        Items: 261,262x64,262x64
    Medic:
        Armor: 298,303,304,305
        Items: 283,6,322x4,6,373:16389,373:16389,373:16385
    Magician:
        Armor: 6,6
        Items: 268,6,373:8258,6,6,373:16388,373:16392,373:16394,373:16396
```

**Comment by aarontwf** [comment]
Firstly [upgrade to 1.4.0](http://dev.bukkit.org/server-mods/battlenight/files/17-battle-night-v1-4-0/).  The file you posed looks fine but add in the classes you want to the file and I'll check it for you.

**Comment by ghost** [comment]
soz i thought it was in there
upgrading now here is classes.yml:http://pastebin.com/0u43PmXb

**Comment by aarontwf** [comment]
Found the issue.  There is an extra space here as well as some missing spaces after the colon:

```
...
    Magician:
        Armor: 6,6
       Items:268,6,373:8258,6,6,373:16388,373:16392,373:16394,373:16396
...
```

Here's a fixed version of your file:

```
# BattleNight Version: 1.4.0
# Classes Configuration File
#
# Add Classes as you wish but do not use spaces in names.
# Items are i:dxa, i=Item d=data a=Ammount.  Data and ammount are optional
# Each class must have at least 2 items, use the dummyitem if you only want 1
# The DummyItem can also be used as a spacer (examples bellow)
# Remember, potions can not be stacked
# I have made a searchable Potion ID list available at http://bit.ly/potionlist

DummyItem: 6

Classes:
    Pyro:
        Armor: 298,299,300,301
        Items: 259,46x2,6,6,6,6,6,6,373:8195
    Tank:
        Armor: 310,311,312,313
        Items: 272,6
    Swordsman:
        Armor: 306,307,308,309
        Items: 276,6,6,6,6,6,6,6,373:8233
    Archer:
        Armor: 302,303,304,305
        Items: 261,262x64,262x64
    Medic:
        Armor: 298,303,304,305
        Items: 283,6,322x4,6,373:16389,373:16389,373:16385
    Magician:
        Armor: 6,6
        Items: 268,6,373:8258,6,6,373:16388,373:16392,373:16394,373:16396
    Samurai:
        Armor: 302,303,304,305
        Items: 267,6
    Ninja:
        Armor: 35:15,6
        Items: 261,262:64,272
```
