### ISSUE TITLE
Classes problem

### ISSUE THREAD

**Issue by geekyhamster** [aarontwf/BattleNight-Core#67]
hi on different account now!
thanks for the fixed classes.yml but now...
i can pick class and the name goes on the sign but i don't get my items!

**Comment by aarontwf** [comment]
A common issue is the classes don't get loaded properly.  Try a <code>/bn reload</code>.

**Comment by geekyhamster** [comment]
Done
still broken

**Comment by aarontwf** [comment]
Any error messages in the console?

**Comment by geekyhamster** [comment]
2 errors
one when i bn reload
one when i pick class
both are at http://pastebin.com/R9cF69Ph

**Comment by aarontwf** [comment]
There is an error in your classes.yml file.  Post the text it in `<code></code>` tags here and ill fix it for you.

**Comment by geekyhamster** [comment]
```
# BattleNight Version: 1.4.0
# Classes Configuration File
DummyItem: 6
Classes:
    Scout:
        Armor: 6,6
        Items: 268,6,6,6,6,6,373:8226,373:8226,373:8226
    Pyro:
        Armor: 298,299,300,301
        Items: 259,46x2,6,6,6,6,6,6,373:8195
    Tank:
        Armor: 310,311,312,313
        Items: 272,6
    Swordsman:
        Armor: 6,6
        Items: 276,6,6,6,6,6,6,6,373:8233
    Archer:
        Armor: 302,303,304,305
        Items: 261,368x8,6,6,6,6,6,262x64,262x64
    Medic:
        Armor: 298,303,304,305
        Items: 283,6,322x4,6,373:16389,373:16389,373:16385
    Magician:
        Armor: 306,307,308,309
        Items: 272,368x4,6,373:16386,6,6,373:16396,373:16388,373:16458
    Spy:
        Armor: 6,6
        Items: 267,373:8258
    Ninja:
        Armor: 35:15,6
        Items: 261,262:64,272
    Samurai:
        Armor: 302,303,304,305
        Items: 267,6
```
