### ISSUE TITLE
Cannot tp to lounges

### ISSUE THREAD

**Issue by McF4rtson** [aarontwf/BattleNight-Core#76]
Any players who aren't opped cannot teleport to the lounge.

When /bn join is typed, the non-opped plaers can join a team, but are never moved to the lounges. I checked all of the permissions for Battlenight, and they were fine.

I suspect it is a permissions problem.

Other permission plugins I use are: PermissionsBukkit, as well as the default permissions.yml

Here are the perms:

PermissionsBukkit configuration file

``` yaml
users:
    McF4rtson:
        permissions:
            permissions.*: true
        groups:
        - owner
    chocomilkmachine:
        permissions:
            permissions.*: true
        groups:
        - admin
    treeoflight:
        permissions:
            sortal.createwarp: true
            sortal.placesign: true
            sortal.delwarp: true
            worldedit.*: true
            essentials.tp: true
            essentials.tp.others: true
            essentials.vanish: true
            essentials.weather: true
            auras.*: true
            bukkit.command.ban.list: true
            bukkit.command.teleport: true
            bukkit.command.xp: true
            bukkit.command.give: true
            bukkit.command.kick: true
            bukkit.command.help: true
            bukkit.command.toggledownfall: true
            essentials.enchant: true
            essentials.enchant.[enchantmentname]: true
            essentials.fly: true
            essentials.joinfullserver: true
            essentials.heal: true
            essentials.heal.cooldown.bypass: true
            essentials.heal.others: true
            essentials.feed: true
            essentials.feed.others: true
            essentials.tempban: true
            essentials.gamemode: true
        groups:
        - mod
    noah_silvera:
        permissions:
            essentials.warp: true
            ddeckys.nodrop.exempt: true
            Gold2Economy.gold: true
            Gold2Economy.3411: true
            essentials.spawn: true
            sortal.warp: true
            auras.smoke: true
            permissions.build: true
            magicspells.silent: true
            essentials.sethome: true
            essentials.home: true
            essentials.clearinventory: true
            airportal.use: true
            battlenight.user: true
            kit.kit: true
            kit.starter: true
            magicspells.cast.*: true
            magicspells.learn.*: true
            magicspells.grant.*: true
            magicspells.noreagents: true
            skillz.skill.Digging: true
            skillz.skill.Swimming: true
            bukkit.command.tell: true
            essentials.balance: true
            essentials.pay: true
            essentials.sell: true
            essentials.worth: true
            essentials.afk: true
            fe.member: true
            pvparena.user: true
        groups:
        - user
    marine8714:
        permissions:
            essentials.warp: true
            ddeckys.nodrop.exempt: true
            Gold2Economy.gold: true
            Gold2Economy.3411: true
            essentials.spawn: true
            sortal.warp: true
            auras.smoke: true
            permissions.build: true
            magicspells.silent: true
            essentials.sethome: true
            essentials.home: true
            essentials.clearinventory: true
            airportal.use: true
            battlenight.user: true
            kit.kit: true
            kit.starter: true
            magicspells.cast.*: true
            magicspells.learn.*: true
            magicspells.grant.*: true
            magicspells.noreagents: true
            skillz.skill.Digging: true
            skillz.skill.Swimming: true
            bukkit.command.tell: true
            essentials.balance: true
            essentials.pay: true
            essentials.sell: true
            essentials.worth: true
            essentials.afk: true
            fe.member: true
            pvparena.user: true
        groups:
        - user
    sjpratt1:
        permissions:
            essentials.warp: true
            ddeckys.nodrop.exempt: true
            Gold2Economy.gold: true
            Gold2Economy.3411: true
            essentials.spawn: true
            sortal.warp: true
            auras.smoke: true
            permissions.build: true
            magicspells.silent: true
            essentials.sethome: true
            essentials.home: true
            essentials.clearinventory: true
            airportal.use: true
            battlenight.user: true
            kit.kit: true
            kit.starter: true
            magicspells.cast.*: true
            magicspells.learn.*: true
            magicspells.grant.*: true
            magicspells.noreagents: true
            skillz.skill.Digging: true
            skillz.skill.Swimming: true
            bukkit.command.tell: true
            essentials.balance: true
            essentials.pay: true
            essentials.sell: true
            essentials.worth: true
            essentials.afk: true
            fe.member: true
            pvparena.user: true
        groups:
        - user
groups:
    owner:
        permissions:
            permissions.*: true
        inheritance:
        - mod
    admin:
        permissions:
            permissions.*: true
        inheritance:
        - mod
    user:
        permissions:
            essentials.warp: true
            ddeckys.nodrop.exempt: true
            Gold2Economy.gold: true
            Gold2Economy.3411: true
            essentials.spawn: true
            sortal.warp: true
            auras.smoke: true
            permissions.build: true
            magicspells.silent: true
            essentials.sethome: true
            essentials.home: true
            essentials.clearinventory: true
            airportal.use: true
            battlenight.user: true
            kit.kit: true
            kit.starter: true
            magicspells.cast.*: true
            magicspells.learn.*: true
            magicspells.grant.*: true
            magicspells.noreagents: true
            skillz.skill.Digging: true
            skillz.skill.Swimming: true
            bukkit.command.tell: true
            essentials.balance: true
            essentials.pay: true
            essentials.sell: true
            essentials.worth: true
            essentials.afk: true
            fe.member: true
            pvparena.user: true
    builder-VIP:
        permissions:
            lwc.protect: true
            kit.kit: true
            kit.builder: true
            quicksign.colorsignchange: true
            quicksign.colordyes: true
            quicksign.use: true
            worldedit.navigation.unstuck: true
            worldedit.navigation.up: true
            worldedit.selection.pos: true
            worldedit.clipboard.cut: true
            worldedit.fixlava: true
            worldedit.fixwater: true
            worldedit.extinguish: true
            worldedit.remove: true
            worldedit.snow: true
            worldedit.thaw: true
            worldedit.history.redo: true
            worldedit.history.undo: true
            skillz.skill.Mining: true
            skillz.skill.Woodcutting: true
            skillz.skill.Farming: true
        inheritance:
        - user
    fighter-VIP:
        permissions:
            lwc.protect: true
            kit.kit: true
            kit.fighter: true
            auras.flames: true
            monsterbox.eggset: true
            monsterbox.eggspawn.*: true
            skillz.skill.Archery: true
            skillz.skill.Axes Combat: true
            skillz.skill.Swords Combat: true
            skillz.skill.Unarmed Combat: true
        inheritance:
        - default
    VIP-II:
        permissions:
            essentials.setwarp: true
            essentials.delwarp: true
            auras.enderman: true
            auras.flames: true
            skillz.skill.Acrobatics: true
            worldedit.region.walls: true
            worldedit.region.faces: true
            worldedit.region.naturalize: true
            worldedit.region.smooth: true
            worldedit.generation.cylinder: true
            worldedit.generation.sphere: true
            worldedit.generation.forest: true
            worldedit.generation.pyramid: true
            worldedit.drain: true
            worldedit.butcher: true
            worldedit.superpickaxe: true
            QuickID.id: true
            kit.kit: true
            kit.ultimate: true
        inheritance:
        - builder-VIP
        - fighter-VIP
    mod:
        permissions:
            sortal.createwarp: true
            sortal.placesign: true
            sortal.delwarp: true
            worldedit.*: true
            essentials.tp: true
            essentials.tp.others: true
            essentials.vanish: true
            essentials.weather: true
            auras.*: true
            bukkit.command.ban.list: true
            bukkit.command.teleport: true
            bukkit.command.xp: true
            bukkit.command.give: true
            bukkit.command.kick: true
            bukkit.command.help: true
            bukkit.command.toggledownfall: true
            essentials.enchant: true
            essentials.enchant.[enchantmentname]: true
            essentials.fly: true
            essentials.joinfullserver: true
            essentials.heal: true
            essentials.heal.cooldown.bypass: true
            essentials.heal.others: true
            essentials.feed: true
            essentials.feed.others: true
            essentials.tempban: true
            essentials.gamemode: true
        inheritance:
        - VIP-II
messages:
    build: '&cYou do not have permission to build here.'

debug: false
```
